    <link rel="stylesheet" href="./css/main.css">
    <link rel="stylesheet" href="./css/index.css">
    <link rel="stylesheet" href="./blocks/css/main-top.css">
    <link rel="stylesheet" href="./templates/css/continue.css">
    <link rel="stylesheet" href="./templates/css/banner-card.css">
    <link rel="stylesheet" href="./templates/css/header.css">
    <link rel="stylesheet" href="./templates/css/footer.css">
    <link rel="stylesheet" href="./blocks/css/genre-titles.css">
    <link rel="stylesheet" href="./templates/css/big-card.css">
    <link rel="stylesheet" href="./templates/css/rate.css">
    <link rel="stylesheet" href="./templates/css/small-card.css">
    <link rel="stylesheet" href="./blocks/css/rating.css">
    <link rel="stylesheet" href="./templates/css/genre-card.css">
    <link rel="stylesheet" href="./blocks/css/genres.css">